stayease:
  title: Stay Easy API
  description: API do módulo Stay Easy
  version: 0.0.1-SNAPSHOT
  endpointsPackage: br.com.stayease

server:
  port: 5000

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: 'health,info'

spring:
  application:
    name: StayEasy API
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 50
  flyway:
    enabled: true
    schemas: stayeasy
    locations: classpath:db/common,classpath:db/migration
  datasource:
    url: jdbc:postgresql://localhost:5433/stayeasy
    username: postgres
    password: postgres
    hikari:
      pool-name: stayeasy-pool
      idle-timeout: 120000
      maximum-pool-size: 10
      minimum-idle: 5
      max-lifetime: 300000
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    open-in-view: false
    database: postgresql
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.hbm2ddl.auto: validate
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.jdbc.time_zone: UTC
      hibernate.default_schema: stayeasy
api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}
